iiif-prezi/iiif-prezi3

setup.py

I think the URL is wrong in setup.py so the link in PyPI is broken. This should fix that.

fixing the url to the repository so it is updated in PyPI

---

iiif_prezi3/base.py
tests/test_basic.py

The user can now change the values of the IIIF object after it has been instantiated using the reference to the original object.
```python
from iiif_prezi3 import Canvas, Manifest
originalID = 'http://iiif.example.org/TESTORIGINAL'
amanifest = Manifest(id='http://iiif.example.org/prezi/Manifest/0', type='Manifest', label={'en': ['default label']})
acanvas = Canvas(id='http://iiif.example.org/prezi/Manifest/0/canvas/01', type='Canvas', label={'en': ['default label']})
asecondcanvas = Canvas(id=originalID, type='Canvas', label={'en': ['second label']})
changedID = 'http://iiif.example.org/TESTCHANGED'
amanifest.items = [acanvas, asecondcanvas]
acanvas.id = changedID
amanifest.items[0].id, changedID
```
This should fix: https://github.com/iiif-prezi/iiif-prezi3/issues/35

Disable deep copy of nested object, allowing to change properties of instances inside classes after their instantiation

---

iiif_prezi3/base.py
tests/test_basic.py

This PR adds the `.jsonld()`and `.jsonld_dict()` functions to the base pydantic model. It also overrides the `.json()` function and replaces it with `.jsonld()`
Closes #27

add jsonld function to base model

---

iiif_prezi3/helpers/auto_fields.py
tests/test_helpers_autofields.py

Add tests for auto_field helper, and make uuid a slug, not a full URN (which is invalid according to pydantic)

add tests for auto field helpers

---

iiif_prezi3/loader.py

This updates the monkeypatcher to allow passing a list of Schema objects as well as a single one.
```python
from ..loader import monkeypatch_schema
from ..skeleton import Manifest, Canvas
class ExampleHelper:
def example_helper(self):
return "First Example"
class ExampleHelper2:
def example_helper2(self):
return "Second example
monkeypatch_schema(Manifest, ExampleHelper)
monkeypatch_schema([Manifest, Canvas], ExampleHelper2)
```

Update monkeypatch to handle list of Schema classes

---

.github/workflows/ci.yml

I noticed the cache key had the wrong filename for the dev requirements. 
Although I can't tell if the dev requirements are being used anywhere... should they be?

Correct dev requirements path in cache key

---

iiif_prezi3/base.py

e.g. for duration or other wrapped types

allow int and float root types

---

.github/workflows/docs.yml
CONTRIBUTING.md
README.md
docs/README.md
docs/code.md
iiif_prezi3/helpers/add_label.py
iiif_prezi3/helpers/canvas_helpers.py
mkdocs.yml
setup.py

this pr adds basic documentation setup
- docs dependencies added as extra / optional install in setup.py
- very basic `mkdocs` setup; pulled in the existing `docs/*.md` files, linked the main readme to be the index of the docs site, added a code reference file to generate docs from code docstrings using google format
- added notes to contributing file about docstring format and instructions for building docs locally
- github action to publish mkdocs —based on https://github.com/marketplace/actions/deploy-mkdocs ; not sure how to test this before merging! at minimum a maintainer will need to configure a `GITHUB_TOKEN` secret to allow the deploy
should be possible to create PR check to confirm documentation builds correctly, and maybe even check documentation coverage, but I'm less familiar …

Basic mkdocs documentation setup

---

iiif_prezi3/base.py

The inclusion of `exclude_unset=True` in the JSON producing functions was preventing non-modified defaults (such as `type` from being included in the JSON output.
This PR fixes that, and also explicitly sets `exclude_defaults` to `False` and prevents it from being overridden by the kwargs.

Fix accidental exclusion of default values

---

iiif_prezi3/helpers/__init__.py
iiif_prezi3/helpers/add_metadata.py
tests/test_add_metadata.py

https://github.com/iiif-prezi/iiif-prezi3/issues/38
AddMetadata class with tests

#38 add metadata

---

.github/workflows/ci.yml
setup.py

Python 3.11 was released at the end of October - this PR adds it to the testing matrix in `ci.yml` and lists it as a supported version in `setup.py`

Add Python 3.11 to the testing matrix and supported versions

---

README.md

Since `README.md` was first written, we have fixed various issues and updated some library behaviour, so this PR brings the listed examples up to date with current behaviour:
* Remove the `exclude_unset=True` arguments as we now enforce in the `.json()` and `.jsonld()` functions.
* Add the labels to the outputs, as they now correctly appear
* Get rid of the `iiif_prezi3.__version__` example, as this is no longer valid
* Adds `@context` key to the examples

Update the examples in `README.md` to reflect current behaviour

---

iiif_prezi3/base.py

Updates the way we handle arguments in the `.jsonld()` function (and therefore in the `.json()` wrapper) and adds `by_alias=True` to the enforced arguments to Pydantic
Closes #95

Json argument fix

---

.github/workflows/PyPi.yml
.github/workflows/TestPyPi.yml
.github/workflows/ci.yml
.github/workflows/docs.yml

Bumps GitHub actions versions:
- `actions/checkout` to v3
- `actions/setup-python` to v4
- `actions/cache` to v3
fixes #99

Bump GH action versions

---

README.md

Adds instructions to README on how to install for local development and how to write an extension.
Closes #71 
Closes #7

Add local development + extension instructions

---

iiif_prezi3/helpers/canvas_helpers.py
tests/test_canvas_helpers.py

Passes any additional kwargs in `add_image` to the `AnnotationItem` created.

Pass additional properties to AnnotationItem

---

iiif_prezi3/helpers/create_canvas_from_iiif.py

Uses the correct name for `create_canvas_from_iiif()` in `make_canvas_from_iiif()`.
fixes #110

Correct name of function in `make_canvas_from_iiif` helper

---

iiif_prezi3/helpers/canvas_helpers.py
tests/test_canvas_helpers.py

Changes target of image to (correctly) target Canvas URI rather than the image URI. Also updates tests.
Fixes #108

Target canvas id

---

.flake8

Moves comments in the `ignore` section to their own lines
Closes #118

Fix flake8 config to work with flake8 6.0.0

---

mkdocs.yml

to address #130
I looked at this briefly locally — it looks like we need to configure the default handler for `mkdocstrings` to be `python`
Attaching a screenshot of the beginning of the code docs page that I built locally with this config

Configure python as default handler for mkdocstrings

---

docs/recipes/0001-mvm-image.md
docs/recipes/0002-mvm-audio.md
docs/recipes/0003-mvm-video.md
docs/recipes/0004-canvas-size.md
docs/recipes/0005-image-service.md
docs/recipes/0006-text-language.md
docs/recipes/0007-string-formats.md
docs/recipes/0008-rights.md
docs/recipes/0009-book-1.md
docs/recipes/0010-book-2-viewing-direction.md
docs/recipes/0011-book-3-behavior.md
docs/recipes/0015-start.md
docs/recipes/0019-html-in-annotations.md
docs/recipes/0021-tagging.md

This PR brings in the completed cookbook recipe examples.
We could hold off merge until more are completed, from the `cookbook_skeletons` branch, which can then be PR-ed into this branch to be added to this PR before merge to main.

Cookbook recipe examples

---

iiif_prezi3/helpers/annotation_helpers.py
iiif_prezi3/helpers/create_canvas_from_iiif.py

Adds arguments for Annotation and AnnotationPage.
I didn't add **kwargs for `AnnotationHelpers.add_annotation` because we're already passing in a pre-fab Annotation object, so since we're not creating an Annotation from scratch it makes less sense to do that (IMO). Happy to be contradicted though.
Fixes #111

Adds args for intermediate objects

---

.github/workflows/ci.yml
iiif_prezi3/base.py
tests/test_basic.py
tests/test_canvas_helpers.py
tests/test_create_canvas_from_iiif.py
tox.ini

Allowing tox to build the sdist means it deals with installing the dependencies in each environment. Combined this with manually specifying that the `dev` extras should be installed in the linter environment.
This should mean we no longer need to keep tox.ini up to date when our requirements change and so removes both workload/remembering and potential issues caused by differing versions when developing and testing (such as the Pydantic `deep_copy` issue) :tada: 
Closes #98

Switch tox to using package dependencies

---

utils/modify_skeleton.py
utils/regenerate_skeleton.py

Adds 2 utilities in a new `utils` folder:
1) Skeleton modifier - this makes the required changes to the existing skeleton file (see #94)
2) Skeleton regenerator - this downloads the latest JSON Schema from the validator repo, regenerates the Skeleton file, and then runs the modifier

Skeleton utilities

---

iiif_prezi3/base.py

Please see extensive discussion in Slack starting here: https://iiif.slack.com/archives/C04EWD70FCH/p1678557314842839
tl;dr - there was an edge case in the handling of our current workaround to make Pydantic's `__root__` construct invisible that prevented it (nested roots with a list at the property level) and this fixes that

Update getattribute handling to work with root-having items inside a list

---

iiif_prezi3/base.py
tests/test_basic.py

Implements an optional `exclude_context` method to calls to `.json()`, and restructures the base class to wrap the json/jsonld calls the other way around.
Closes #128

Optional context argument

---

docs/recipes/scripts/0001-mvm-image-method1.py
docs/recipes/scripts/0001-mvm-image-method2.py
docs/recipes/scripts/0002-mvm-audio-method1.py
docs/recipes/scripts/0003-mvm-video-method1.py
docs/recipes/scripts/0004-canvas-size-method1.py
docs/recipes/scripts/0005-image-service-method1.py
docs/recipes/scripts/0006-text-language-method1.py
docs/recipes/scripts/0007-string-formats-method1.py
docs/recipes/scripts/0008-rights-method1.py
docs/recipes/scripts/0009-book-1-method1.py
docs/recipes/scripts/0010-book-2-viewing-direction-method1-example1.py
docs/recipes/scripts/0010-book-2-viewing-direction-method1-example2.py
docs/recipes/scripts/0011-book-3-behavior-method1-usecase1.py
docs/recipes/scripts/0011-book-3-behavior-method1-usecase2.py
docs/recipes/scripts/0015-start-method1.py
docs/recipes/scripts/0017-transcription-av-method1.py
docs/recipes/scripts/0019-html-in-annotations-method1.py
docs/recipes/scripts/0021-tagging-method1.py
docs/recipes/scripts/0118-multivalue-method1.py
docs/recipes/scripts/0230-navdate-method1-example1.py
docs/recipes/scripts/0230-navdate-method1-example2.py
docs/recipes/scripts/0230-navdate-method1-example3.py
docs/recipes/scripts/0230-navdate-method2-example1.py
docs/recipes/scripts/0230-navdate-method2-example2.py
docs/recipes/scripts/0230-navdate-method2-example3.py
docs/recipes/scripts/0261-non-rectangular-commenting-method1.py

Picking up on an idea I used during my [dogfooding of the "Introduction to `iiif-prezi3`" lightning talk](https://digitaldogsbody.net/iiif/prezi3): due to the structure of the recipes, there are a lot of `id` fields that have a common start, so this PR adds a `base_url` variable and uses it in the various bits of manifest data, meaning that the resulting code looks a bit less cluttered (IMO)

Update recipes to use a `base_url` variable to improve readability

---

docs/recipes/0047-homepage.md
docs/recipes/scripts/0047-homepage-method1.py

This adds a recipe using HomepageItem and tries to help `none` and `en` labels as elegantly as possible.

Add recipe for 0047 Homepage.

---

docs/recipes/0014-accompanyingcanvas.md
docs/recipes/scripts/0014-accompanyingcanvas-method1.py
iiif_prezi3/helpers/add_item.py
tests/test_add_item.py

1. This adds a solution for Recipe 0014.
2. Attempts to address [Issue 199](https://github.com/iiif-prezi/iiif-prezi3/issues/199) by making add_item() available to AccompanyingCanvas.
3. Adds a test to check that members of items in AccompanyingCanvas are AnnotationPages when added with `add_item()`.

Add Recipe 0014 and add add_item() to AccompanyingCanvas

---

docs/recipes/0074-multiple-language-captions.md
docs/recipes/scripts/0074-multiple-language-captions-method1.py

Add recipe for 0074 Multiple Language Captions.

---

iiif_prezi3/helpers/set_hwd_from_iiif.py
tests/test_set_hwd_from_iiif.py

This should solve: https://github.com/iiif-prezi/iiif-prezi3/issues/218

An attempt to solve Issue 218 for caching requests 

---

docs/recipes/0029-metadata-anywhere.md
docs/recipes/scripts/0029-metadata-anywhere-method1.py

Adds a solution for the Metadata Anywhere Recipe.

Address Metadata Anywhere recipe.

---

docs/recipes/0033-choice.md
docs/recipes/scripts/0033-choice-method1.py
iiif_prezi3/helpers/auto_fields.py

This targets task 0033 [here](https://github.com/iiif-prezi/iiif-prezi3/issues/129) and adds a solution using `Choice` and the `add_item` helper.  It might also serve as a solution for [Issue-192](https://github.com/iiif-prezi/iiif-prezi3/issues/192) although maybe not as gracefully as what the user would like.
One note is that I could not get labels with auto configs to add directly to ResourceItems, so I created [this_issue](https://github.com/iiif-prezi/iiif-prezi3/issues/213) and was forced to use `add_label`. Assuming I didn't make a mistake, this is something we should look into.

Init solution for recipe_0033.

---

iiif_prezi3/helpers/auto_fields.py
iiif_prezi3/helpers/make_manifest.py
tests/test_make_manifest.py

This attempts to address [Issue-191](https://github.com/iiif-prezi/iiif-prezi3/issues/191).  That issue describes a problem where `homepage` props are dropped from Manifests in a Collection if the manifest was created via the `make_ manifest()` helper.  Oddly, the issue doesn't exist if manifests are created and added to the Collection in other ways.
The issue appears to be that the helper uses the `Manifest` class rather than `ManifestRef`.  If we switch the classes, things seem to work as expected.  
Todo: **what if items prop exists in incoming kwargs?**
I don't think so. I've added ManifestRef to the AutoIdConfig helper incase someone was using `make_manifest()` without adding an `id` property since that worked on Manifest but not ManifestRef.  I've also had to add `ManifestRef` to …

Attempt to address Issue-191.

---

iiif_prezi3/helpers/add_thumbnail.py
tests/test_add_thumbnail.py

This adds a new helper  on `AddThumbnail` called `create_thumbnail_from_iiif()`. This allows someone to generate a thumbnail from an image info response that is v2 or v3.  It optionally takes an argument `preferred_width` that will choose the best thumbnail if a `sizes` property exists in the info.json (defaults to 500). If no `sizes` property exists, it just takes the full sized image as `full/full` for v2 or `full/max` for v3. This seems like the safest way to approach in case of a level 0 image service.
Some of the patterns here are inspired by previous helpers, but I chose to add the method to the existing AddThumbnail class rather than create a brand  new helper class from scratch.  My thinking about this was to try and keep all thumbnail helpers together. I'd like to add another …

Create Thumbnail from IIIF

---

iiif_prezi3/helpers/make_collection.py
iiif_prezi3/helpers/make_manifest.py
tests/test_make_collection.py

This makes `MakeCollection` create a Collection when there are items or a CollectionRef when there are not. It also pops `items` on data for `MakeManifest` so that we don't accidentally end up with an embedded Manifest.  This is needed due to an issue with `Reference` and `extra.allow`.

Attempt to Address Issue-225 and Issue-226.

---

iiif_prezi3/base.py

This addresses an issue related to deprecation of a vlue as of Pydantic v2.  Previously the value was set to `False` but it's been updated to the new value of `none`.

Address Issue-232.

---

tests/test_schema.py

Closes #250 and allows support of https://iiif.io/api/cookbook/recipe/0258-tagging-external-resource/. Note changes already made in schema this just adds a test

Checking schema update has support for optional selector
